[workspace]
members = [
    "contracts/credit-score",
    "contracts/loan", 
    "contracts/collateral",
    "contracts/swap",
    "contracts/fee-manager",
    "contracts/liquidity",
    "contracts/oracle",
    "contracts/multisig",
    "contracts/storage-manager",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = "21.0.0"
soroban-token-sdk = "0.5.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true